webhook:
  url: 'https://discord.com/api/webhooks/{webhook.id}/{webhook.token}'
  embed_icon: 'https://gitlab.com/ayush-sharma/to-the-fediverse/-/raw/master/static/images/icon.png'

bridges: 
  - name: '@username@example.com' # or whatever you want it to be called
    host: 'example.com'
    user_id: '1234567890'
    
  - name: '@username@example.com' # or whatever you want it to be called
    host: 'example.com'
    user_id: '1234567890'

  - name: '@username@example.com' # or whatever you want it to be called
    host: 'example.com'
    user_id: '1234567890'